{
  description = "Generated by nixpick";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { nixpkgs, ... }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});
    in {
      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            # Pin the Flutter minor line explicitly instead of the floating
            # `flutter` attribute so the dev shell stays on a stable, older
            # release (3.44 line) that is broadly available. The bare `flutter`
            # tracks nixpkgs-unstable and can jump to a newer version that some
            # environments cannot fetch yet.
            flutter344
            (python3.withPackages (pythonPackages: with pythonPackages; [
              fastapi
              httpx
              pytest
              uvicorn
            ]))
          ];
        };
      });
    };
}
